# Generated by Django 4.1.4 on 2022-12-09 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_tag_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-12-09 08:47:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
